# Generated by Django 4.1.7 on 2023-07-24 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Dough', 'Dough'), ('Spicery', 'Spicery'), ('Sauce', 'Sauce'), ('Meat_products', 'Meat Products'), ('Cheese', 'Cheese')], max_length=20)),
                ('time', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ingredients',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredient',
            },
        ),
    ]
