# Generated by Django 4.2.2 on 2023-08-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.ManyToManyField(related_name='cheeses', to='ingredients.ingredients')),
                ('dough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crusts', to='ingredients.ingredients')),
                ('meat_products', models.ManyToManyField(related_name='meat_products', to='ingredients.ingredients')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='ingredients.ingredients')),
                ('spicery', models.ManyToManyField(related_name='spices', to='ingredients.ingredients')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
