# Generated by Django 4.2.2 on 2023-08-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_cooking_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
