# Generated by Django 4.2.2 on 2023-08-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredients_id_ingredients_new_id'),
        ('orders', '0004_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cheese',
            field=models.ManyToManyField(related_name='cheese', to='ingredients.ingredients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dough', to='ingredients.ingredients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauce', to='ingredients.ingredients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='spicery',
            field=models.ManyToManyField(related_name='spicery', to='ingredients.ingredients'),
        ),
    ]
