# Generated by Django 4.2.2 on 2023-08-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredients_id'),
        ('orders', '0005_alter_order_cheese_alter_order_dough_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cheese',
            field=models.ManyToManyField(related_name='cheeses', to='ingredients.ingredients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crusts', to='ingredients.ingredients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='ingredients.ingredients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='spicery',
            field=models.ManyToManyField(related_name='spices', to='ingredients.ingredients'),
        ),
    ]
