# Generated by Django 4.2.2 on 2023-08-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredients_id_ingredients_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='new_id',
            new_name='id',
        ),
    ]
